export const initialNodes = [
  {
    id: "manual_trigger_node",
    category: "trigger",
    type: "manual",
    position: { x: 0, y: 0 },
    data: { label: "매뉴얼 트리거", imageUrl: "nodeImages/touch_app.svg" },
  },
  {
    id: "chat_trigger_node",
    category: "trigger",
    type: "chat",
    position: { x: 0, y: 0 },
    data: { label: "챗 트리거", imageUrl: "nodeImages/touch_app.svg" },
  },
  {
    id: "schedule_trigger_node",
    category: "trigger",
    type: "schedule",
    position: { x: 0, y: 0 },
    data: { label: "스케줄 트리거", imageUrl: "nodeImages/touch_app.svg" },
  },
  {
    id: "search_node",
    category: "action",
    type: "azure_search",
    position: { x: 0, y: 0 },
    data: { label: "Azure Search", imageUrl: "nodeImages/document_search.svg" },
  },
  {
    id: "generate_answer",
    category: "agent",
    type: "llm_call",
    position: { x: 0, y: 0 },
    data: { label: "Agent 호출", imageUrl: "nodeImages/chat.svg" },
  },
  {
    id: "aggregator",
    category: "utility",
    type: "aggregator",
    position: { x: 0, y: 0 },
    data: { label: "Aggregator", imageUrl: "nodeImages/edit.svg" },
  },
  {
    id: "condition",
    category: "control_flow",
    type: "condition",
    position: { x: 0, y: 0 },
    data: { label: "if/else", imageUrl: "nodeImages/call_split.svg" },
  },
  {
    id: "while_loop",
    category: "control_flow",
    type: "while",
    position: { x: 0, y: 0 },
    data: { label: "while문", imageUrl: "nodeImages/call_split.svg" },
  },
  {
    id: "for_loop",
    category: "control_flow",
    type: "foreach",
    position: { x: 0, y: 0 },
    data: { label: "for문", imageUrl: "nodeImages/call_split.svg" },
  },
  {
    id: "autonomous",
    category: "agent",
    type: "autonomous_agent",
    position: { x: 0, y: 0 },
    data: { label: "Autonomous Agent", imageUrl: "nodeImages/call_split.svg" },
  },
  {
    id: "final_output",
    category: "action",
    type: "output",
    position: { x: 0, y: 0 },
    data: { label: "최종 출력", imageUrl: "nodeImages/call_split.svg" },
  },
  {
    id: "transform",
    category: "action",
    type: "data_transform",
    position: { x: 0, y: 0 },
    data: { label: "데이터 변환", imageUrl: "nodeImages/call_split.svg" },
  },
  {
    id: "report_template",
    category: "action",
    type: "report_template",
    position: { x: 0, y: 0 },
    data: { label: "정형 보고서 생성", imageUrl: "nodeImages/call_split.svg" },
  },
  {
    id: "chart",
    category: "action",
    type: "chart",
    position: { x: 0, y: 0 },
    data: { label: "차트 생성", imageUrl: "nodeImages/call_split.svg" },
  },
  {
    id: "mcp",
    category: "action",
    type: "mcp",
    position: { x: 0, y: 0 },
    data: { label: "MCP 연결", imageUrl: "nodeImages/call_split.svg" },
  },
];
